# Site settings
site: Furkan Bilgin
title:  Personal Research Blog - Windows, Linux, System, Devops, Cloud
keywords:  Furkan Bilgin, blog, Windows, Linux ,System, Devops, Cloud
description: >-
   Furkan Bilgin Personal Blog
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/furkanbilgin/furkanbilgin.github.io # site repo [optional]
google_verify:      XX # Put your Google Verification here
google_analytics:   UA-73661033-5 # Put your Google Analytics code
discus-identifier: XX

# Author settings
author:
  name:  Furkan Bilgin
  bio: Cloud & System Devops Engineer @Digiturk / Formerly System Manager @Tekhnelogos </br> Founder @SentezOfis </br> TB1FBI </br> furkanbilgin@windowslive.com
  picture: assets/img/furkan-bilgin.jpg
  github: furkanbilgin # github username
  twitter: furkanbilginn # twitter username
  facebook: furkanbilgin # facebook username
  instagram: furkanbilginn # instagram username
  linkedin: furkanbilgin # instagram username
  email: furkanbilgin@windowslive.com # email adress


# URL settings
url: "https://furkanbilgin.com" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false