title: Hello, world! I'm Furkan Bilgin
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Furkan Bilgin # add your name
author-img: furkan-bilgin.jpg # add your photo
about-author: System Manager @Tekhnelogos | Founder @Sentez Ofis
social-twitter: furkanbilginn
social-facebook: furkanbilgin
social-github: furkanbilgin # add your Github handle
social-linkedin: furkanbilgin
social-email: furkanbilgin@windowslive.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-73661033-5 # Google Analytics


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
